name: CI
on:
  # To be fixed
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
jobs:
  build:
    name: test Node ${{ matrix.node }} ${{ matrix.os }}
    timeout-minutes: 15

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x']
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: ${{ matrix.node }}
          package-manager-cache: false

      - name: Install Pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          run_install: true

      - name: Test
        run: npm test -- --forceExit || npm test -- --forceExit || npm test -- --forceExit
